### ISSUE TITLE
New submission: Tone King | TRI TUBE PREAMP

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#102]
```
brand: Tone King
model: TRI TUBE PREAMP
email: ecmaj7@gmail.com
url: ''
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: BYPASS ON
    value: '24'
    description: Pre-amp Bypassed
    min: '1'
    max: '1'
  - name: BYPASS OFF
    value: '24'
    description: Pre-amp Engaged
    min: 0
    max: '0'
  - name: RHYTHM CHANNEL
    value: '25'
    description: Rhythm Channel On
    min: 0
    max: '0'
  - name: LEAD CHANNEL
    value: '25'
    description: Lead Channel On
    min: '1'
    max: '1'
  - name: LOOP BYPASS ON
    value: '26'
    description: Effects Loop Bypassed
    min: '1'
    max: '1'
  - name: LOOP BYPASS OFF
    value: '26'
    description: Effects Loop Engaged
    min: 0
    max: '0'
  - name: IR BYPASS ON
    value: '27'
    description: Speaker Impulse Response Bypassed
    min: '127'
    max: 127
  - name: IR BYPASS OFF
    value: '27'
    description: Speaker Impulse Response Engaged
    min: 0
    max: '0'
  - name: CAB 1
    value: '28'
    description: Speaker Cab 1
    min: 0
    max: '0'
  - name: CAB 2
    value: '28'
    description: Speaker Cab 2
    min: '1'
    max: '1'
  - name: CAB 3
    value: '28'
    description: Speaker Cab 3
    min: '2'
    max: '2'
  - name: HF COMP ON
    value: '29'
    description: High Frequency Compensation On
    min: '1'
    max: '1'
  - name: HF COMP OFF
    value: '29'
    description: High Frequency Compensation Off
    min: 0
    max: '0'
  - name: LOWPASS 1
    value: '30'
    description: Lowpass Filter 1
    min: 0
    max: '0'
  - name: LOWPASS 2
    value: '30'
    description: Lowpass Filter 2
    min: '1'
    max: '1'
  - name: LOWPASS 3
    value: '30'
    description: Lowpass Filter 3
    min: '2'
    max: '2'
  - name: REVERB ON
    value: '31'
    description: Reverb On
    min: '1'
    max: '1'
  - name: REVERB OFF
    value: '31'
    description: Reverb Off
    min: 0
    max: '0'
  - name: TREMOLO ON
    value: '32'
    description: Tremolo On
    min: '1'
    max: '1'
  - name: TREMOLO OFF
    value: '32'
    description: Tremolo Off
    min: 0
    max: '0'

```
