### ISSUE TITLE
[Proposal]: CC definitions for value and range mappings

### ISSUE THREAD

**Issue by yuhrao** [Morningstar-Engineering/openmidi#49]
Many devices has specific falue mappings for configuration.
Let's take Strymon BigSky as example:

CC 33 (Chorale - Vowel) has this value mapping:

|value|description|
|----:|-----------|
|0    | "AAHHOO"  |
|1    | "AAHH"    |
|2    | "AAHHOH"  |
|3    | "OH"      |
|4    | "OOOHOH"  |
|5    | "OOOO"    |
|6    | Random    |

At same time we also have some devices that work with ranges, like HX Stopm:

CC 61 (1 Switch Looper Play/Stop):

| range |description|
|------:|-----------|
|0-63   | Stop      |
|64-127 | Play      |

My proposal is to extend the CC schema to be able to represent those values in a more plesant way for the end user and also priovide a better experience for those who consume it via code.

```yaml
cc:
  - name: 'Chorale - Vowel'
    value: 33
    min: 0
    max: 6
    description: 'some description'
    type: Parameter
    value_mapping:
      0: AAHHOO
      1: AAHH
      2: AAHHOH
      3: OH
      4: OOOHOH
      5: OOOO
      6: Random
  - name: 'Switch Looper Play/Stop'
    value: 61
    min: 0
    max: 6
    description: 'some description'
    type: Parameter
    range_mapping:
      - min: 0
        max: 63
        description: Stop
      - min: 64
        max: 127
        description: Play
```

**Comment by yuhrao** [comment]
I saw that the same applies for PC parameters. For EHX we have a range for change program and specific values for some parameters:

```yaml
pc:
  description: 'some description'
  range_mapping:
    - min: 0
      max: 99
      description: Loop selection
  value_mapping:
    100: PLAY FSW
    101: RESET FSW
```
