### ISSUE TITLE
New submission from openMIDI 

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#66]
```
brand: test
model: tset
email: test
url: test
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: geawg
    value: 0
    description: egae
    min: 0
    max: 127

```
