### ISSUE TITLE
New submission: test | este

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#74]
```
brand: test
model: este
email: james@morningstarfx.com
url: test
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: teatew
    value: 0
    description: ''
    min: 0
    max: 127

```
