### ISSUE TITLE
New submission: TC Electronic | Nova Drive NDR-1

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#79]
```
brand: TC Electronic
model: Nova Drive NDR-1
email: kristine@morningstarfx.com
url: 'https://toneprints.com/media/217955/nova_drive_manual_us.pdf'
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: OD On/Off
    value: '21'
    description: 0 - 63 = Off ; 64 - 127 = On
    min: 0
    max: 127
  - name: Dist On/Off
    value: '22'
    description: '0 - 63 = Off ; 64 - 127 = On '
    min: 0
    max: 127
  - name: OD Drive
    value: '23'
    description: ''
    min: 0
    max: 127
  - name: OD Level
    value: '24'
    description: ''
    min: 0
    max: 127
  - name: OD Tone
    value: '25'
    description: ''
    min: 0
    max: 127
  - name: OD Mix
    value: '26'
    description: ''
    min: 0
    max: 127
  - name: Dist Drive
    value: '27'
    description: ''
    min: 0
    max: 127
  - name: Dist Level
    value: '28'
    description: ''
    min: 0
    max: 127
  - name: Dist Bass
    value: '29'
    description: ''
    min: 0
    max: 127
  - name: Dist Treble
    value: '30'
    description: ''
    min: 0
    max: 127
  - name: Routing
    value: '31'
    description: >-
      0 - 42 = Overdrive into Distortion ; 43 - 84 = Distortion into Overdrive
      ;  85 - 127 = Distortion and Overdrive in Parallel
    min: 0
    max: 127

```
