### ISSUE TITLE
New submission: Chase Bliss Audio | Brothers AM

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#90]
```
brand: Chase Bliss Audio
model: Brothers AM
email: kristine@morningstarfx.com
url: >-
  https://static1.squarespace.com/static/622176a9b8d15d57ffbf5700/t/67fd54d41a39143df84b920d/1744655572913/Brothers+AM_MIDI+Manual_Pedal_Chase+Bliss.pdf
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: GAIN 2
    value: '14'
    description: ''
    min: 0
    max: 127
  - name: VOLUME 2
    value: '15'
    description: ''
    min: 0
    max: 127
  - name: GAIN 1
    value: '16'
    description: ''
    min: 0
    max: 127
  - name: TONE 2
    value: '17'
    description: ''
    min: 0
    max: 127
  - name: VOLUME 1
    value: '18'
    description: ''
    min: 0
    max: 127
  - name: TONE 1
    value: '19'
    description: ''
    min: 0
    max: 127
  - name: PRESENCE 2
    value: '27'
    description: ''
    min: 0
    max: 127
  - name: PRESENCE 1
    value: '29'
    description: ''
    min: 0
    max: 127
  - name: GAIN 2 TYPE
    value: '21'
    description: BOOST = 0 - 1 ; OD = 2 ; DIST = 3 OR >
    min: 0
    max: 127
  - name: TREBLE BOOST
    value: '22'
    description: FULL SUN = 0 - 1 ; OFF = 2 ; HALF SUN = 3 OR >
    min: 0
    max: 127
  - name: GAIN 1 TYPE
    value: '23'
    description: DIST = 0 - 1 ; OD = 2 ; BOOST = 3 OR >
    min: 0
    max: 127
  - name: CHANNEL 2 BYPASS
    value: '102'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: CHANNEL 1 BYPASS
    value: '103'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: EOM (EXPRESSION OVER MIDI)
    value: '100'
    description: ''
    min: 0
    max: 127
  - name: PRESET SAVE
    value: '111'
    description: ''
    min: '1'
    max: '122'
  - name: VOLUME 1
    value: '61'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: VOLUME 2
    value: '62'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: GAIN 1
    value: '63'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: TONE 1
    value: '65'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: TONE 2
    value: '66'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: SWEEP
    value: '67'
    description: B = 0 ; T = 1 or >
    min: 0
    max: 127
  - name: POLARITY
    value: '68'
    description: F = 0 ; R = 1 or >
    min: 0
    max: 127
  - name: HI GAIN 1
    value: '71'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: HI GAIN 2
    value: '72'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: MOTOBYP 1
    value: '73'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: MOTOBYP 2
    value: '74'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: PRES LINK 1
    value: '75'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: PRES LINK 2
    value: '76'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127
  - name: MASTER
    value: '77'
    description: OFF = 0 ; ON = 1 or >
    min: 0
    max: 127

```
