### ISSUE TITLE
New submission: Chase Bliss | Brothers AM

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#92]
```
brand: Chase Bliss
model: Brothers AM
email: t.cuozzo@gmail.com
url: >-
  https://static1.squarespace.com/static/622176a9b8d15d57ffbf5700/t/67fd54d41a39143df84b920d/1744655572913/Brothers+AM_MIDI+Manual_Pedal_Chase+Bliss.pdf
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: Gain 2
    value: '14'
    description: ''
    min: 0
    max: 127
  - name: Volume 2
    value: '15'
    description: ''
    min: 0
    max: 127
  - name: Gain 1
    value: '16'
    description: ''
    min: 0
    max: 127
  - name: Tone 2
    value: '17'
    description: ''
    min: 0
    max: 127
  - name: Volume 1
    value: '18'
    description: ''
    min: 0
    max: 127
  - name: Tone 1
    value: '19'
    description: ''
    min: 0
    max: 127
  - name: Presence 2
    value: '27'
    description: ''
    min: 0
    max: 127
  - name: Presence 1
    value: '29'
    description: ''
    min: 0
    max: 127
  - name: Gain 2 Type
    value: '21'
    description: '0, 1 Boost, 2 OD, 3-127 Dist'
    min: 0
    max: 127
  - name: Treble Boost
    value: '22'
    description: '0,1 Full Sun, 2 Off, 3-127 Half Sun'
    min: 0
    max: 127
  - name: Gain 1 Type
    value: '23'
    description: '0, 1 Dist, 2 OD, 3-127 Boost'
    min: 0
    max: 127
  - name: Channel 2 Bypass
    value: '102'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Channel 1 Bypass
    value: '103'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: EOM (Expression Over MIDI)
    value: '100'
    description: ''
    min: 0
    max: 127
  - name: Preset Save
    value: '111'
    description: ''
    min: 0
    max: '122'
  - name: Volume 1 DIP
    value: '61'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Volume 2 DIP
    value: '62'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Gain 1 DIP
    value: '63'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Gain 2 DIP
    value: '64'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Tone 1 DIP
    value: '65'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Tone 2 DIP
    value: '66'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Sweep DIP
    value: '67'
    description: '0 = B, 1-127 = T'
    min: 0
    max: 127
  - name: Polarity DIP
    value: '68'
    description: '0 = F, 1-127 = R'
    min: 0
    max: 127
  - name: Hi Gain 1 DIP
    value: '71'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Hi Gain 2 DIP
    value: '72'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: MOTOBYP 1 DIP
    value: '73'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: MOTOBYP 2 DIP
    value: '74'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Pres Link 1 DIP
    value: '75'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Pres Link 2 DIP
    value: '76'
    description: '0 off, 1-127 on'
    min: 0
    max: 127
  - name: Master DIP
    value: '77'
    description: '0 off, 1-127 on'
    min: 0
    max: 127

```
