### ISSUE TITLE
New submission: Line 6 | HX One

### ISSUE THREAD

**Issue by tyzjames** [Morningstar-Engineering/openmidi#93]
```
brand: Line 6
model: HX One
email: joseph.j.tam@gmail.com
url: >-
  https://line6.com/support/page/kb/effects-controllers/helix/helixhx-380-release-notes-r1079/
midi_channel:
  instructions: ''
midi_clock: unknown
midi_in: unknown
midi_thru: unknown
pc:
  description: ''
phantom_power: unknown
midi_mapping: not applicable
cc:
  - name: Preset Navigation
    value: '72'
    description: >-
      0-63: Previous preset; 64-127: Next preset (added in firmware version
      3.80)
    min: 0
    max: 127

```
